title: "VBBSKW"
description: "Blog"
baseurl: "" 
url: "https://www.vbbskw.com"

plugins:
  - jekyll-feed

sass:
  style: compressed

# Collecties voor participatie nieuws
collections:
  nieuws:
    output: true
    permalink: /nieuws/:title/

